services:
  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/nginx-cache:/var/cache/nginx
    depends_on:
      - apache
    networks:
      - nginx-net

  apache:
    build: ./apache
    container_name: apache-server
    ports:
      - "8080:80"
    networks:
      - nginx-net

networks:
  nginx-net:
    driver: bridge
